version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_database
      - PGDATA=/var/lib/postgresql/data/name/
    volumes:
      - data-volume:/var/lib/postgresql/data

  backend:
    restart: always
    environment:
      - POSTGRES_HOST=postgres
    container_name: backend
    depends_on:
      - postgres
    build:
      context: ./server
    ports:
      - 8080:8080
      - 8081:8081

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./client
    ports:
      - 3000:3000

volumes:
  data-volume:
